# Generated by Django 3.0.7 on 2020-06-27 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20200627_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
